"""Generates and caches a downloadable statement PDF.

The mock MIB backend has no real transaction ledger, so the line items here
are fabricated — deterministically, seeded from the operation's tx_id, so
downloading the same completed operation twice returns the identical file.
Swap `_mock_rows` for a real transaction export once MIB exposes one; nothing
else in the pipeline (chat.py, the document router, the web gateway) needs to
change — they only ever deal in tx_id and raw PDF bytes.

Generated bytes are cached in Redis (base64, like the other ad-hoc state in
this service layer) under a short TTL — long enough to download, not a
permanent document store.
"""
import base64
import hashlib
import logging
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

import redis.asyncio as aioredis
from fpdf import FPDF

from orchestrator.config import settings
from orchestrator.services import accounts, speechtext

logger = logging.getLogger("orchestrator.statement_pdf")

redis = aioredis.from_url(settings.REDIS_URL, decode_responses=True)

_TTL = 3600  # seconds a generated PDF stays downloadable

_PERIOD_DAYS = {"week": 7, "month": 30, "quarter": 90, "year": 365}

# (description, sign) — mundane, plausible line items for a fabricated demo
# statement; +1 credit, -1 debit.
_MOCK_ROWS = [
    ("Salary", 1), ("Grocery Store", -1), ("Utility Payment", -1),
    ("Online Transfer", -1), ("Restaurant", -1), ("Pharmacy", -1),
    ("ATM Withdrawal", -1), ("Mobile Top-up", -1), ("Subscription", -1),
    ("Refund", 1),
]

_LABELS = {
    "ru-RU": {"brand": "ForteBank — голосовой ассистент AI-nur",
              "title": "Выписка по счёту", "account": "Счёт", "period": "Период",
              "date": "Дата", "desc": "Операция", "amount": "Сумма", "total": "Итого"},
    "kk-KZ": {"brand": "ForteBank — AI-nur дауыстық ассистенті",
              "title": "Шот бойынша үзінді", "account": "Шот", "period": "Кезең",
              "date": "Күні", "desc": "Операция", "amount": "Сома", "total": "Қорытынды"},
    "en-US": {"brand": "ForteBank — AI-nur voice assistant",
              "title": "Account Statement", "account": "Account", "period": "Period",
              "date": "Date", "desc": "Transaction", "amount": "Amount", "total": "Total"},
}

# Unicode (Cyrillic-capable) font candidates, in preference order: fpdf2's
# built-in core fonts are Latin-1 only and can't render Russian/Kazakh text.
# Linux entry matches fonts-dejavu-core, installed in orchestrator/Dockerfile;
# Windows entry covers local dev.
_FONT_CANDIDATES = [
    ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
     "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    (r"C:\Windows\Fonts\arial.ttf", r"C:\Windows\Fonts\arialbd.ttf"),
]


def _key(tx_id: str) -> str:
    return f"statement_pdf:{tx_id}"


def _mock_rows(tx_id: str, period: str) -> list[dict]:
    """Deterministic pseudo-random rows seeded from tx_id, so re-downloading
    the same operation always returns the same statement."""
    days = _PERIOD_DAYS.get(period, 30)
    seed = int(hashlib.sha256(tx_id.encode()).hexdigest(), 16)
    rng = random.Random(seed)
    now = datetime.now(timezone.utc)
    rows = []
    for _ in range(rng.randint(6, 12)):
        name, sign = rng.choice(_MOCK_ROWS)
        rows.append({
            "date": now - timedelta(days=rng.randint(0, days)),
            "desc": name,
            "amount": sign * rng.randint(1500, 95000),
        })
    rows.sort(key=lambda r: r["date"], reverse=True)
    return rows


def _register_font(pdf: FPDF) -> str:
    """Register a Unicode font from a known path, or fall back to the core
    Latin-1 font (Cyrillic text would then render as blanks/missing glyphs —
    acceptable degradation, not a crash, if no candidate font is installed)."""
    for regular, bold in _FONT_CANDIDATES:
        if Path(regular).exists():
            pdf.add_font("Body", "", regular)
            pdf.add_font("Body", "B", bold if Path(bold).exists() else regular)
            return "Body"
    logger.warning("no Unicode font found — statement PDF falls back to the Latin-1 core font")
    return "helvetica"


def _fmt_amount(value: int, currency: str) -> str:
    sign = "+" if value > 0 else ""
    return f"{sign}{value:,} {currency}".replace(",", " ")


def _build(tx_id: str, period: str, account: dict | None, lang: str) -> bytes:
    labels = _LABELS.get(lang) or _LABELS["ru-RU"]
    period_word = speechtext.for_display({"period": period}, lang)["period"]
    currency = (account or {}).get("currency", "KZT")
    account_name = accounts.display_name(account, lang) if account else "—"

    pdf = FPDF()
    # fpdf2 stamps /CreationDate with the real wall-clock time by default,
    # which would make otherwise-identical output differ byte-for-byte
    # depending on when it happened to be generated. Pin it so the same
    # tx_id always produces the exact same file, matching this module's own
    # "re-downloading returns the identical statement" guarantee.
    pdf.set_creation_date(datetime(2024, 1, 1, tzinfo=timezone.utc))
    pdf.add_page()
    font = _register_font(pdf)

    pdf.set_font(font, "B", 16)
    pdf.set_text_color(192, 22, 108)  # brand magenta
    pdf.cell(0, 11, labels["brand"], new_x="LMARGIN", new_y="NEXT")

    pdf.set_font(font, "B", 13)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 9, labels["title"], new_x="LMARGIN", new_y="NEXT")

    pdf.set_font(font, "", 11)
    pdf.cell(0, 7, f"{labels['account']}: {account_name} ({currency})", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"{labels['period']}: {period_word}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    rows = _mock_rows(tx_id, period)
    col_w = (28, 100, 42)

    pdf.set_font(font, "B", 10)
    pdf.set_fill_color(36, 18, 38)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(col_w[0], 8, labels["date"], fill=True)
    pdf.cell(col_w[1], 8, labels["desc"], fill=True)
    pdf.cell(col_w[2], 8, labels["amount"], fill=True, align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font(font, "", 10)
    pdf.set_text_color(20, 20, 20)
    total = 0
    for i, row in enumerate(rows):
        total += row["amount"]
        pdf.set_fill_color(245, 240, 244) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.cell(col_w[0], 7.5, row["date"].strftime("%d.%m.%Y"), fill=True)
        pdf.cell(col_w[1], 7.5, row["desc"], fill=True)
        pdf.cell(col_w[2], 7.5, _fmt_amount(row["amount"], currency), fill=True, align="R",
                  new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    pdf.set_font(font, "B", 11)
    pdf.cell(col_w[0] + col_w[1], 8, labels["total"])
    pdf.cell(col_w[2], 8, _fmt_amount(total, currency), align="R")

    return bytes(pdf.output())


async def generate_and_store(
    tx_id: str, session_id: str, params: dict, lang: str
) -> bool:
    """Build the PDF for a just-completed statement_pdf operation and cache
    it under tx_id. Best-effort: a failure here must never break the
    operation reply itself, so callers only get a bool, not an exception."""
    try:
        account = None
        account_id = params.get("account_id")
        user_accounts = await accounts.list_accounts(session_id)
        if account_id:
            account = next(
                (a for a in user_accounts if a.get("account_id") == account_id), None
            )
        if account is None and user_accounts:
            account = user_accounts[0]

        pdf_bytes = _build(tx_id, params.get("period", "month"), account, lang)
        await redis.setex(_key(tx_id), _TTL, base64.b64encode(pdf_bytes).decode())
        return True
    except Exception as e:  # noqa: BLE001 — best-effort, like history.record
        logger.error("statement PDF generation failed for tx_id=%s: %s", tx_id, e)
        return False


async def fetch(tx_id: str) -> bytes | None:
    """Return the cached PDF bytes for tx_id, or None if missing/expired."""
    raw = await redis.get(_key(tx_id))
    if raw is None:
        return None
    return base64.b64decode(raw)
